{"name": "test_login_invalid_user[test_info0]", "status": "broken", "statusDetails": {"message": "TypeError: find_element() argument after * must be an iterable, not NoneType", "trace": "self = <test_cases.test_001_login.TestLogin object at 0x000002368684E8C8>\ntest_info = {'expected': '请选择机构!', 'pwd': '123456', 'user': 'ceshiehdej'}\nget_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"419006badb3278287559bafe4693394a\")>\n\n    @pytest.mark.parametrize('test_info', login_data_invalid)\n    @allure.story(\"用户名不存在\")\n    def test_login_invalid_user(self, test_info, get_browser):\n        print(\"------执行登录用户名不存在测试用例------\")\n        driver = get_browser\n        expected = test_info['expected']\n>       LoginPage(driver).login(test_info[\"user\"], test_info[\"pwd\"])\n\ntest_001_login.py:56: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\login_page.py:42: in login\n    self.move_click(btn_elem)\n..\\common\\base_page.py:161: in move_click\n    ele= self.wait_clickable_element(locator)\n..\\common\\base_page.py:82: in wait_clickable_element\n    EC.element_to_be_clickable(locator)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"419006badb3278287559bafe4693394a\")>\nby = None\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() argument after * must be an iterable, not NoneType\n\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "attachments": [{"name": "log", "source": "d2f6c372-1096-4692-b6f1-6ddffa65d4cf-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_info", "value": "{'user': 'ceshiehdej', 'pwd': '123456', 'expected': '请选择机构!'}"}], "start": 1600343700595, "stop": 1600343709687, "uuid": "b7b17381-8842-439b-b13a-c4afda3000e3", "historyId": "075f4daf5ac51fdca2fb54fe12eff52f", "testCaseId": "cd0682f6a139d5392c369302963db253", "fullName": "test_cases.test_001_login.TestLogin#test_login_invalid_user", "labels": [{"name": "story", "value": "用户名不存在"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_001_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-G986QGRS"}, {"name": "thread", "value": "22432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_001_login"}]}